from jax import random as rand


DEFAULT_DT = 0.01
DEFAULT_TOTAL_TIME = 10.
DEFAULT_V0 = 1.
DEFAULT_TRANSLATION_GAMMA = 0.1
DEFAULT_TRANSLATION_DIFFUSION = 1.
DEFAULT_ROTATION_GAMMA = 0.01
DEFAULT_ROTATION_DIFFUSION = 0.1
DEFAULT_OMEGA = 0.
DEFAULT_POISSON_ANGLE_REASSIGNMENT_RATE = 3.
